<?php

/*
 * "aa.php" is a self-contained attribute authority for adding attributes to the
 * accounts generated by the account_gen module. This is useful for testing different entitlements
 *
 * Attributes are stored in a simple PHP array that is serialised in JSON format to disk after each change.
 * A SimpleSAMLphp authproc is used to read the attributes from disk and add them when the user authenticates
*/

require_once('sp-utils.inc');

define('AA_FILE', __DIR__ . '/../data/aa.json'); // I.e. /var/www/simplesaml/data/aa.json

// Result of the last action to display to the user
$action_result = '';
$action_error = false;

// Load the attributes from disk
// Array format: [ { 'u': 'user1', 'a': 'attr1', 'v': 'value1' }, ... ]
$attributes = [];
if (file_exists(AA_FILE)) {
    $attributes = json_decode(file_get_contents(AA_FILE), true);
    if (false === $attributes) {
        $action_result = 'Failed to load attributes';
        $action_error = true;
        $attributes = [];
    }
}

$bAttributesChanged = false;

// Process form submission
if (isset($_POST['action'])) {
    // ADD action
    if ( ($_POST['action'] == 'add') && (!$action_error)) {
        $username = $_POST['username'] ?? '';
        if (!$username) {
            $action_result = 'Username is required';
            $action_error = true;
        }
        $attribute = $_POST['attribute'] ?? '';
        if (!$attribute) {
            $action_result = 'Attribute name is required';
            $action_error = true;
        }
        $value = $_POST['value'] ?? '';
        if (!$value) {
            $action_result = 'Attribute value is required';
            $action_error = true;
        }

        // Add the new attribute to the array
        if (!$action_error) {
            $attributes[] = ['u' => $username, 'a' => $attribute, 'v' => $value];

            $bAttributesChanged = true;
            $action_result = 'Attribute added';
        }
    }

    // DELETE action
    if ( ($_POST['action'] == 'delete') && (!$action_error)) {
        $idx = $_POST['idx'] ?? [];
        if (!is_array($idx)) {
            $idx = [$idx];
        }
        $nrDeleted = 0;
        foreach ($idx as $i) {
            if (isset($attributes[$i])) {
                unset($attributes[$i]);
                $bAttributesChanged = true;
                $nrDeleted++;
            }
        }

        if ($nrDeleted == 0) {
            $action_result = 'No attributes deleted';
            $action_error = true;
        }

        if ($nrDeleted > 1) {
            $count = count($idx);
            $action_result = "$nrDeleted of $count attributes deleted";
        }
    }

    // DELETE ALL action
    if ( ($_POST['action'] == 'delete all') && (!$action_error)) {
        $attributes = [];
        $bAttributesChanged = true;
        $action_result = 'All attributes deleted';
    }

    // Save changes to disk
    if ($bAttributesChanged) {
        // Sort the attributes by username, then attribute name, then attribute value
        // This will also reindex the array
        usort($attributes, function($a, $b) {
            if ($a['u'] != $b['u']) {
                return strcmp($a['u'], $b['u']);
            }
            if ($a['a'] != $b['a']) {
                return strcmp($a['a'], $b['a']);
            }
            return strcmp($a['v'], $b['v']);
        });

        // Save to disk
        $result = file_put_contents(AA_FILE, json_encode($attributes, JSON_PRETTY_PRINT));
        if ($result === false) {
            $action_result = 'Failed to save attributes';
            $action_error = true;
        }
    }
}

// Table and form for adding/deleting attributes
echo <<<HTML
<html>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
		<style type="text/css">
		    body {font-family: arial, verdana, sans-serif; margin: 0px}
		    h1,h2,h3,h4 {background-color: lightgray; padding: 2px 10px; border-top: 1px solid; border-bottom: 1px solid; clear: both}
		    table { border-collapse: collapse}
		    table,th,td {border: 1px solid black}
		    th,td {padding-top: 1px; padding-bottom: 1px; padding-left: 4px; padding-right: 4px; font-size: 12px}
		    label {width:220px; font-size: 14px; margin-right: 10px; display: inline-block; float: left; text-align: right}
		    code {display: inline-block; max-width: 600px; float: left; margin-top: 2px;}
		    small {display: inline-block; max-width: 600px; float: left}
		    p,div {margin: 10px; clear: both}
		    button { border-radius: 4px; font-weight: bold; font-size: 14px; background-color: lightgrey; color: black; border: 1px solid black; padding: 5px 10px}
		    button.add {background-color: darkseagreen}
		    button.delete {background-color: indianred}
		    select {min-width: 150px; font-size: 14px;}
		    input {min-width: 140px; font-size: 14px;}
		    input[type="submit"] {min-width: 100px; font-size: 14px;}
		    input[type="checkbox"] {min-width: 20px; font-size: 14px;}
		    input[type="text"] {min-width: 400px; font-size: 14px;}
        </style>    
        <title>Attribute Authority</title>
    </head>
    <body>
        <h1>Attribute Authority</h1>
HTML;

if ($action_result) {
    if ($action_error) {
        echo "<div id='error'><p style='color: red'><code>$action_result</code></p></div>";
    } else {
        echo "<div id='message'><p style='color: green'><code>$action_result</code></p></div>";
    }
    echo "<br />";
}

// Display form for adding an attribute
echo <<<HTML
        <form method="post">
            <h2>Add Attribute</h2>
            <p>
                <label
                    title="The username (uid) of the account to add the attribute to. E.g. 'joa-a1'" 
                    for="username">Username (uid):</label>
                <input id="uid" type="text" name="username" id="username">
            </p>
            <p>
                <datalist id="attributes">
                    <option value="urn:mace:dir:attribute-def:eduPersonEntitlement" />
                </datalist>
                <label
                    title="The name of the attribute to add. E.g. 'urn:mace:dir:attribute-def:eduPersonEntitlement'" 
                    for="attribute">Attribute Name:</label>
                <input id="name" type="text" name="attribute" id="attribute" list="attributes">
            </p>
            <p>
                <label
                    title="The value of the attribute to add. E.g. 'urn:mace:surf.nl:surfsecureid:activation:self'. To set multiple values for an attribute, add the attribute multiple times." 
                    for="value">Attribute Value:</label>
                <datalist id="values">
                    <option value="urn:mace:surf.nl:surfsecureid:activation:self" />
                    <option value="urn:mace:surf.nl:surfsecureid:activation:ra" />
                </datalist> 
                <input id="value" type="text" name="value" id="value" list="values">
            </p>
            <p>
                <input
                    id="add"
                    title="Add the attribute to the list of attributes. Username, attribute name and value are required." 
                    type="submit" name="action" value="add" class="add">
            </p>
        </form>
HTML;

// Display table/form with the current attributes, add a checkbox to each row to select which attributes to delete
echo <<<HTML
        <h2>Current Attributes</h2>
        <p>
            <form method="post">                
                <table>
                    <tr>
                        <th>Select</th>
                        <th>Username (uid)</th>
                        <th>Attribute Name</th>
                        <th>Attribute Value</th>
                    </tr>
HTML;

foreach ($attributes as $idx => $attr) {
    $attribute_name = $attr['a'] ?? '';
    $attribute_value = $attr['v'] ?? '';
    $username = $attr['u'] ?? '';
    echo <<<HTML
                    <tr>
                        <td><input type="checkbox" name="idx[]" value="$idx"></td>
                        <td>$username</td>            
                        <td>$attribute_name</td>
                        <td>$attribute_value</td>
                    </tr>
HTML;
}

echo <<<HTML
                </table>
                <p>
                    <input
                        id="delete"
                        title="Delete the selected attribute(s) from the list of attributes." 
                        type="submit" name="action" value="delete" class="delete">
                    <input
                        id="delete_all"
                        title="Delete all attributes." 
                        type="submit" name="action" value="delete all" class="delete">
                </p>
            </form>
         </p>
     </body>
</html>
HTML;

